; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ESP32dev]
platform = espressif32 @6.12.0
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
board_upload.wait_for_upload_port = yes
build_flags = "-Os"
	 -DCORE_DEBUG_LEVEL=2
lib_deps = 
	Wire
	SPI
	tzapu/WiFiManager@^2.0.17
	exocet22/btAudio@^1.1.0

[platformio]
description = Echoes of Termina Bluetooth Speaker V0.1