[env:arduinosp32-c3]
platform = espressif32@6.11.0
platform_packages = 
  	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.1
  	framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.1/esp32-arduino-libs-3.0.1.zip
	;tool-esptoolpy @ 4.7.6 
	;tool-mklittlefs @ 3.2.0 
	;tool-riscv32-esp-elf-gdb @ 11.2.0+20220823 
	;tool-xtensa-esp-elf-gdb @ 11.2.0+20230208 
	;toolchain-riscv32-esp @ 12.2.0+20230208
board = esp32-c3-devkitm-1
board_build.flash_mode = qio
board_upload.before_reset = usb_reset
framework = arduino ;@ 3.0.4+sha.147836c 
;upload_port = /dev/cu.usbmodem323101
;upload_protocol = esp-builtin
;upload_port = COM6
;upload_protocol = espota
upload_port = 192.168.3.31
;upload_port = marajoara-devkit.local
monitor_port = COM7
upload_speed = 460800
;upload_speed = 512000
monitor_speed = 115200
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
	Wire
	SPI
	adafruit/Adafruit ADS1X15@^2.4.0
	adafruit/Adafruit BusIO@^1.14.5
	adafruit/Adafruit GFX Library@^1.11.9
	adafruit/Adafruit SSD1306@^2.5.7
	adafruit/Adafruit NeoPixel@^1.12.0
	tzapu/WiFiManager@^2.0.17